### ISSUE TITLE
Logout when browser close

### ISSUE THREAD

**Issue by webtuts4u** [cartalyst/sentinel#379] opened 2017-08-03 03:24 UTC
Facing an issue, user still showing login after close the browser. But all the session is cleared still shown login. When user again open the browser then still showing login with his/her credentials. but data is not loaded on view because all the session is cleared. Need to logout the user when they close the browser and require to login again.
`
'lifetime' => 60,
'expire_on_close' => true,
`
These are the session settings. Hard to trace the issue. Suggest me where i am doing mistake.

**Comment by brunogaspar** [comment] 2017-08-03 11:39
Hello

I'm not being able to reproduce your issue.

Please let us know what versions are you using of both the Laravel Framework and Sentinel and on which browsers the issue is happening.

If you also have a way to reproduce the code easily, that's also good to let us know.

---

This is what i have and what i tried.

## Versions

- Laravel 5.4.31
- Sentinel 2.0.15
- Chrome 59.0.3071.115 (Official Build) (64-bit)
- Firefox 53.0.3 (64-bit)

## Code

```php
<?php

Route::get('/', function () {
    dump(app('sentinel')->check());
});

Route::get('login', function () {
    app('sentinel')->authenticate([
        'email' => 'foo@bar',
        'password' => 'password',
    ]);

    return redirect('/');
});

Route::get('register', function () {
    app('sentinel')->registerAndActivate([
        'email' => 'foo@bar',
        'password' => 'password',
    ]);

    return redirect('/');
});
```

## Tests

- Setting the `expire_on_close` to `true` and fully closing the browser window, clears all the sessions for me and the next time i open the home page i'm logged out.

- Setting the `expire_on_close` to `false` and fully closing the browser window, keeps all the sessions and the next time i open the home page i'm logged in, which is the expected behaviour.

**Closed by brunogaspar** 2017-08-03 11:39 UTC
Labels: Bug, Invalid
