### ISSUE TITLE
Laravel 7 composer install error

### ISSUE THREAD

**Issue by cuneydtural** [cartalyst/sentinel#534] opened 2020-06-10 08:43 UTC
I get this error in Laravel 7. Help please.

Argument 1 passed to Cartalyst\Sentinel\Activations\IlluminateActivationRepository::__construct() must be of the type string, null given, called in /home/vagrant/ego/vendor/cartalyst/sentinel/src/Laravel/SentinelServiceProvider.php on line 243

  at vendor/cartalyst/sentinel/src/Activations/IlluminateActivationRepository.php:54
    50|      * @param int    $expires
    51|      *
    52|      * @return void
    53|      */
  > 54|     public function __construct(string $model, int $expires)
    55|     {
    56|         $this->model = $model;
    57| 
    58|         $this->expires = $expires;

### Your Environment

- OS and Version: #.#.#
- PHP Version: #.#.#
- Sentinel Version: #.#.#

### Expected behaviour

*Please describe what you are expecting to see happening.*

### Actual behaviour

*Please describe what is actually happening.*

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

**Comment by brunogaspar** [comment] 2020-06-10 08:48
This seems to be the same as https://github.com/cartalyst/sentinel/issues/520

If you have a fix please send a pull request as i personally can't reproduce the issue.

Going to close this since it's a duplicate either way.

**Closed by brunogaspar** 2020-06-10 08:48 UTC
