### ISSUE TITLE
Sentinel::guest() always returns true.

### ISSUE THREAD

**Issue by jelledijkstra97** [cartalyst/sentinel#504] opened 2019-09-25 11:00 UTC
### Your Environment

- OS and Version: MacOS localhost
- PHP Version: 7.2
- Sentinel Version: 3.0

### Expected behaviour

I expect the auth middleware to use my signed in user.

I have a Laravel 6.0 app thats uses Sentinel for authentication. I can succesfully log in however after redirecting to my home page a auth middleware redirects me back to the login page. After log in a new row is inserted in the persistences table and inside my session a variable called 'cartalyst_sentinel' is stored with the same value as the persistence row.

When I call Sentinel::findByPersistenceCode with the session code inside the middleware, the current user is returned, however one line later Sentinel::guest() returns true.

Auth controller:
```
<?php namespace Schedules\Http\Controllers;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Illuminate\Http\Request;
use Lang;
use Laracasts\Flash\Flash;
use Log;
use Illuminate\Support\Facades\Session;
use Activation;

/**
 * Class AuthController
 * @package Schedules\Http\Controllers
 */
class AuthController extends Controller
{
    /**
     * AuthController constructor.
     */
    function __construct()
    {
        $this->middleware('guest', ['except' => 'getLogout']);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getLogin()
    {
        return view('auth.login');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function postLogin(Request $request)
    {
        $credentials = $request->except(['_token']);

        if (empty($credentials['email']) || empty($credentials['password'])) {
            Flash::error(Lang::get('auth.messages.empty_fields'));
            return redirect('login');
        }

        if (Sentinel::authenticate($credentials, true)) {
            log::debug("Succesfully logged in");
            Log::debug(Sentinel::getUser()); // This prints the correct user
            return redirect('/');
        } else {
            Flash::error(Lang::get('auth.messages.invalid_login'));
        }

        return redirect('login');
    }

    /**
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function getLogout()
    {
        Sentinel::logout(null, true);

        return redirect('login');
    }

}
```

Auth middleware:
```
<?php namespace Schedules\Http\Middleware;

use Cartalyst\Sentinel\Laravel\Facades\Sentinel;
use Closure;
use Illuminate\Contracts\Auth\Guard;
use Log;
use Session;

class Authenticate {

	/**
	 * The Guard implementation.
	 *
	 * @var Guard
	 */
	protected $auth;

    /**
     * Create a new filter instance.
     *
     * @param  Guard $auth
     */
	public function __construct(Guard $auth)
	{
		$this->auth = $auth;
	}

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \Closure  $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
        $user = Sentinel::findByPersistenceCode(Session::get('cartalyst_sentinel'));
        Log::debug($user); // This prints the correct user

        if (Sentinel::guest())
		{
			if ($request->ajax())
			{
				return response('Unauthorized.', 401);
			}
			else
			{
				return redirect()->guest('login');
			}
		}

		return $next($request);
	}

}
```

In both parts the correct user is printed to my log. But after that Sentinel::guest() returns true. 

How can this be?

**Comment by suwardany** [comment] 2019-09-26 00:47
Try to import 

`use Cartalyst\Sentinel\Sentinel;` 

and then replace 

`public function __construct(Guard $auth)` 

with

`public function __construct(Sentinel $auth)` and make use of it instead of the facade.

```
if ($this->auth->guest()) {
...
```

**Comment by jelledijkstra97** [comment] 2019-09-26 07:02
Thanks for the reply!

Unfortunately this did not solve my problem. The docs say to use Cartalyst\Sentinel\Laravel\Facade\Sentinel right?

Any other suggestions?

**Comment by suwardany** [comment] 2019-09-26 13:54
What do you have in the `RedirectIfAuthenticated` class?

**Comment by jelledijkstra97** [comment] 2019-09-26 13:57
```
<?php

namespace Schedules\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;
use Sentinel;

class RedirectIfAuthenticated
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Sentinel::check())
		{
			return redirect('/');
		}

		return $next($request);
    }
}
```

**Comment by brunogaspar** [comment] 2019-10-01 10:39
Can't reproduce this issue:

- Fresh Laravel 6 install using Composer create-project
- Installed Sentinel 3
- Update `.env` file to point to my database
- Removed the default Laravel migrations
- Published Sentinel migrations & ran `php artisan migrate`
- Added similar files as above
- Can login, be redirected and `Sentinel::guest()` returns `false`

Try to reproduce the problem in a fresh Laravel installation, if it occurs, push the exact code to a public repository and link it here please.

Going to close it for now as it seems a problem on your application.

**Closed by brunogaspar** 2019-10-01 10:39 UTC
