### ISSUE TITLE
Trying to access array offset on value of type null on install Sentinel to laravel 7

### ISSUE THREAD

**Issue by runm717123** [cartalyst/sentinel#530] opened 2020-04-17 07:12 UTC
### Your Environment

- OS and Version: windows 10
- PHP Version: 7.4.1
- Sentinel Version: 4.0.0
- Laravel 7.0

### Expected behaviour
when i install via composer, it try to read sentinel's config file which didn't created yet

![image](https://user-images.githubusercontent.com/33694392/79542320-a2fac200-80b5-11ea-88ab-28e8f42c9e35.png)

**Comment by brunogaspar** [comment] 2020-04-17 07:57
Duplicate of #520 

Since i don't have access to a Windows machine to test and you also have the issue, on Windows, feel free to send a pull request that addresses the issue.

Going to close in favor of the older ticket.

**Closed by brunogaspar** 2020-04-17 07:57 UTC
