### ISSUE TITLE
Switched arguments in function call in EloquentUser

### ISSUE THREAD

**Issue by sabas** [cartalyst/sentinel#219] opened 2016-04-11 10:21 UTC
This call failed:
```if (Sentinel::inRole('admin'))```
with error "Fatal error: Call to a member function getRoleId() on integer"

I noticed that the anonymous function in EloquentUser.php has the arguments switched
https://github.com/cartalyst/sentinel/blob/2.0/src/Users/EloquentUser.php#L197

Instead of 
```$role = array_first($this->roles, function ($index, $instance) use ($role) {```
should be
```$role = array_first($this->roles, function ($instance, $index) use ($role) {```

**Comment by suwardany** [comment] 2016-04-11 10:35
Hello @sabas 

I'm unable to reproduce this issue, what version of Sentinel/Laravel are you using?

**Comment by sabas** [comment] 2016-04-11 10:43
I just installed Sentinel [Installing cartalyst/sentinel (dev-master 5440900) / Cloning 5440900274e50de51fe1883d6e2fdac50c05d382] in a new project, outside Laravel.
Here's the relevevant requires from my composer
```
        "cartalyst/sentinel": "2.0.*",
        "illuminate/database": "~5.0",
        "illuminate/events": "^5.2",
        "symfony/http-foundation": "^3.0"
```

**Comment by 614mediagroup** [comment] 2016-06-01 20:15
Same problem here.

**Comment by brunogaspar** [comment] 2016-06-28 14:49
@sabas Are you still experiencing this?

If yes can you please paste a way to reproduce the issue?

**Comment by sabas** [comment] 2016-06-28 15:33
I didn't have the time to update the libraries because I'm using this in production...
I patched as in my original message another time. I wonder if it 's because I'm not using any Laravel library apart from the required illuminate libraries.

**Comment by brunogaspar** [comment] 2016-06-28 15:36
Not really sure.

But if you could give some code to reproduce your issue and the exact dependencies you're using as well as PHP version i can have a look.

**Comment by sabas** [comment] 2016-06-28 16:33
@brunogaspar this can be useful?
https://gist.github.com/sabas/c14bdd7157b7778c54c45da8a6921e02

**Comment by brunogaspar** [comment] 2016-06-28 16:37
@sabas Yup. Can you just let me know your PHP version too?

I'll have a look early tomorrow to see if i can find what's the cause.

**Comment by sabas** [comment] 2016-06-28 17:03
Testing on windows xampp: php 5.6.15
Production on centos: PHP 7.0.6
I have probably similar code on a different php version (like another php 5.6.*) but I haven't it at hand right now

**Comment by brunogaspar** [comment] 2016-06-28 17:07
Awesome! I'll let you know my findings.

**Comment by brunogaspar** [comment] 2016-06-29 12:00
Hello @sabas 

So it seems that Laravel 5.3 swapped the order of the arguments, yet another awesome breaking change from Laravel.

Method on [5.2](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Support/Arr.php#L156-L169) and on [5.3](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Arr.php#L134-L147).

To fix on your case, just change the `minimum-stability` from `dev` to `stable` on your `composer.json` file and run `composer update`.

See if that fixes the issue for you.

---

@suwardany We'll most likely need to have a way to patch this for Laravel 5.3.

**Comment by trideout** [comment] 2016-08-26 19:35
Having this problem as well. Switching from dev to stable breaks a number of other dependencies.

**Comment by trideout** [comment] 2016-08-26 19:53
I've created a PR that will check for the 5.3 behavior and swap the variables. This change should be backwards compatible and non-breaking #271

**Comment by brunogaspar** [comment] 2016-09-07 16:15
I believe this is now fixed.

**Closed by brunogaspar** 2016-09-07 16:15 UTC
Labels: Bug

**Comment by sjzurek** [comment] 2016-09-08 13:43
Confirmed. After `composer update` problem fixed.
